# ![GA Logo](https://camo.githubusercontent.com/6ce15b81c1f06d716d753a61f5db22375fa684da/68747470733a2f2f67612d646173682e73332e616d617a6f6e6177732e636f6d2f70726f64756374696f6e2f6173736574732f6c6f676f2d39663838616536633963333837313639306533333238306663663535376633332e706e67) Naive Bayes

We've looked at the Naive Bayes classifier from a probability point of view. Now let's apply code to it to a natural language processing problem.

### Before we begin... what is natural language processing?

- If I'm explaining this to my non-technical peers, natural language processing is just a way for us to get computers to understand written language the way you and I do.

- If I'm explaining this to someone with a more technical background, natural language processing is a set of tools that represent words as numbers. This is commonly done by feature engineering (i.e. turning words into columns in your dataframe), but more complicated methods exist.

You'll often see natural language processing abbreviated as **NLP**.

You and I will use these social media posts in a Naive Bayes classification model to predict whether a post comes from Twitter or Facebook.

#### First: some data cleaning.

In [1]:
import pandas as pd

In [2]:
# Read in the .csv file.

df = pd.read_csv("./unprocessed_tweets.csv", encoding='latin-1')

In [3]:
# Check out the columns.

[i for i in df.columns]

['_unit_id',
 '_golden',
 '_unit_state',
 '_trusted_judgments',
 '_last_judgment_at',
 'audience',
 'audience:confidence',
 'bias',
 'bias:confidence',
 'message',
 'message:confidence',
 'orig__golden',
 'audience_gold',
 'bias_gold',
 'bioid',
 'embed',
 'id',
 'label',
 'message_gold',
 'source',
 'text']

In [4]:
# See the first five rows.

df.head()

_unit_id  _golden _unit_state  _trusted_judgments _last_judgment_at  \
0  766192484    False   finalized                   1      8/4/15 21:17   
1  766192485    False   finalized                   1      8/4/15 21:20   
2  766192486    False   finalized                   1      8/4/15 21:14   
3  766192487    False   finalized                   1      8/4/15 21:08   
4  766192488    False   finalized                   1      8/4/15 21:26   

   audience  audience:confidence      bias  bias:confidence  message  ...  \
0  national                  1.0  partisan              1.0   policy  ...   
1  national                  1.0  partisan              1.0   attack  ...   
2  national                  1.0   neutral              1.0  support  ...   
3  national                  1.0   neutral              1.0   policy  ...   
4  national                  1.0  partisan              1.0   policy  ...   

   orig__golden  audience_gold  bias_gold    bioid  \
0           NaN            NaN        NaN  R000596   
1           NaN            NaN        NaN  M000355   
2           NaN            NaN        NaN  S001180   
3           NaN            NaN        NaN  C000880   
4           NaN            NaN        NaN  U000038   

                                               embed           id  \
0  <blockquote class="twitter-tweet" width="450">...  3.83249E+17   
1  <blockquote class="twitter-tweet" width="450">...  3.11208E+17   
2  <blockquote class="twitter-tweet" width="450">...  3.39069E+17   
3  <blockquote class="twitter-tweet" width="450">...  2.98528E+17   
4  <blockquote class="twitter-tweet" width="450">...  4.07643E+17   

                                              label message_gold   source  \
0    From: Trey Radel (Representative from Florida)          NaN  twitter   
1     From: Mitch McConnell (Senator from Kentucky)          NaN  twitter   
2  From: Kurt Schrader (Representative from Oregon)          NaN  twitter   
3          From: Michael Crapo (Senator from Idaho)          NaN  twitter   
4          From: Mark Udall (Senator from Colorado)          NaN  twitter   

                                                text  
0  RT @nowthisnews: Rep. Trey Radel (R- #FL) slam...  
1  VIDEO - #Obamacare:  Full of Higher Costs and ...  
2  Please join me today in remembering our fallen...  
3  RT @SenatorLeahy: 1st step toward Senate debat...  
4  .@amazon delivery #drones show need to update ...  

[5 rows x 21 columns]

In [5]:
# Remove all values with an "audience confidence," "bias
# confidence," or "message confidence" score below 1.

# df = df[
#     (df['audience:confidence'] >= 1) & 
#     (df['bias:confidence'] >= 1) & 
#     (df['message:confidence'] >= 1)]
# df
df = df[(df['audience:confidence'] >= 1) & (df['bias:confidence'] >= 1) & (df['message:confidence'] >= 1)]


In [6]:
# Remove extra columns.

df = df[['_unit_id', '_trusted_judgments', 'audience',
         'bias', 'message', 'label', 'source', 'text']]

In [7]:
# Relabel columns.

df.columns = ['unit_id', 'trusted_judgments', 'audience_feature',
              'bias_feature', 'message_feature', 'label_feature',
              'source_feature', 'text_feature']

In [8]:
# Drop NAs.

df.dropna(inplace=True)

In [9]:
# Reset index.

df.reset_index(drop=True, inplace=True)

We have social media data! This includes almost 5,000 messages on either Twitter or Facebook from various politicians. We can use the features we generated to predict things like whether the source is Twitter or Facebook, whether the bias is neutral or partisan, and so on.

In [10]:
# How many rows and columns do we have?

df.shape

(4888, 8)

In [11]:
# View first five rows.

df.head()

unit_id  trusted_judgments audience_feature bias_feature message_feature  \
0  766192484                  1         national     partisan          policy   
1  766192485                  1         national     partisan          attack   
2  766192486                  1         national      neutral         support   
3  766192487                  1         national      neutral          policy   
4  766192488                  1         national     partisan          policy   

                                      label_feature source_feature  \
0    From: Trey Radel (Representative from Florida)        twitter   
1     From: Mitch McConnell (Senator from Kentucky)        twitter   
2  From: Kurt Schrader (Representative from Oregon)        twitter   
3          From: Michael Crapo (Senator from Idaho)        twitter   
4          From: Mark Udall (Senator from Colorado)        twitter   

                                        text_feature  
0  RT @nowthisnews: Rep. Trey Radel (R- #FL) slam...  
1  VIDEO - #Obamacare:  Full of Higher Costs and ...  
2  Please join me today in remembering our fallen...  
3  RT @SenatorLeahy: 1st step toward Senate debat...  
4  .@amazon delivery #drones show need to update ...

You may note that there are some extra symbols in the data. This is a common problem in natural language processing, especially when dealing with social media (think emoji, hashtags, links, etc.), but we're going to ignore that for now.

### Let's use Naive Bayes to predict whether a social media post was featured on Facebook or Twitter.

#### 1. Engineer a feature to turn `source_feature` into a 1/0 column, where 1 indicates `Twitter`.

In [12]:
df['twitter'] = df['source_feature'].map(lambda x: 1 if x == 'twitter' else 0)

#### NOTE: Since we are solving a classification problem, what potential issue should I check for here?

In [13]:
# Check for unbalanced classes.

df['twitter'].value_counts()

0    2497
1    2391
Name: twitter, dtype: int64

#### 2. Split our data into `X` and `y`.

In [14]:
X = df[['text_feature']]
y = df['twitter']

In [15]:
X.head()

text_feature
0  RT @nowthisnews: Rep. Trey Radel (R- #FL) slam...
1  VIDEO - #Obamacare:  Full of Higher Costs and ...
2  Please join me today in remembering our fallen...
3  RT @SenatorLeahy: 1st step toward Senate debat...
4  .@amazon delivery #drones show need to update ...

#### 3. Split our data into training and testing sets.

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.25,
                                                    random_state=42,
                                                    stratify=y)

#### 4. Turn our text into features. [Documentation here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html).

In [17]:
# Import CountVectorizer.
from sklearn.feature_extraction.text import CountVectorizer

# Instantiate our CountVectorizer.
cvec = CountVectorizer(max_features=500)

In [18]:
# Fit our CountVectorizer on the training data and transform training data.
X_train_cvec = pd.DataFrame(
    cvec.fit_transform(X_train['text_feature']).todense(),
    columns=cvec.get_feature_names(),
)

In [19]:
# Transform our testing data with the already-fit CountVectorizer.

X_test_cvec = pd.DataFrame(
    cvec.transform(X_test['text_feature']).todense(),
    columns=cvec.get_feature_names(),
)

In [20]:
X_train_cvec

000  10  11  12  2013  2014  30  about  access  across  ...  yesterday  \
0       0   0   0   0     0     0   0      0       0       0  ...          1   
1       0   0   0   0     0     0   0      0       0       0  ...          0   
2       0   0   0   0     0     0   0      0       0       0  ...          0   
3       0   0   0   0     0     1   0      0       0       0  ...          0   
4       0   0   0   0     0     0   0      0       0       0  ...          0   
...   ...  ..  ..  ..   ...   ...  ..    ...     ...     ...  ...        ...   
3661    0   0   0   0     0     0   0      0       0       0  ...          0   
3662    0   0   0   0     0     0   0      0       0       0  ...          0   
3663    0   0   0   0     0     0   0      0       0       0  ...          0   
3664    0   0   0   0     1     0   0      0       0       0  ...          0   
3665    0   0   0   0     0     0   0      0       0       0  ...          0   

      you  young  your  û_  ûª  ûªm  ûªs  ûªt  ûò  
0       0      0     0   0   0    1    0    0   0  
1       0      0     0   0   0    0    0    0   0  
2       0      0     0   0   0    0    0    0   0  
3       0      0     0   0   0    0    0    0   0  
4       0      0     0   0   0    0    0    0   0  
...   ...    ...   ...  ..  ..  ...  ...  ...  ..  
3661    0      0     0   0   1    0    0    0   0  
3662    1      0     0   0   0    0    0    0   0  
3663    0      0     0   0   0    0    0    0   0  
3664    0      0     0   0   0    0    0    0   0  
3665    0      0     0   0   0    0    0    0   0  

[3666 rows x 500 columns]

#### 4. Fit a Naive Bayes model!

<details><summary> Which Naive Bayes model should we pick, and why? </summary>
    
- The columns of X are all integer counts, so MultinomialNB is the best choice here.
- BernoulliNB is best when we have 0/1 counts in all columns of X. (a.k.a. dummy variables)
- GaussianNB is best when the columns of X are Normally distributed. (Practically, though, it gets used whenever BernoulliNB and MultinomialNB are inappropriate.)
</details>

# Multinomial is for multiple Xs, not multiple Ys

In [21]:
# Import our model!

from sklearn.naive_bayes import MultinomialNB

In [22]:
# Instantiate our model!

nb = MultinomialNB()

Remember earlier that I said we had the opportunity to set priors. We could do so here if we wanted, but we'll stick with the default and allow `sklearn` to estimate priors from the training data directly.

In [23]:
# Fit our model!

model = nb.fit(X_train_cvec, y_train)

In [24]:
# Generate our predictions!

predictions = model.predict(X_test_cvec)

<details><summary> How might we evaluate our model's performance? </summary>

- Accuracy = (TP + TN) / (TP + TN + FP + FN)
- Sensitivity = TP / (TP + FN)
- Specificity = TN / (TN + FP)
- Precision = TP / (TP + FP)
- AUC ROC
</details>

<details><summary> If we have to select only one, which one should we choose? </summary>

- It depends on how exactly you define "positive" and "negative." In this case, it probably doesn't really matter - incorrectly mistaking a tweet for a Facebook post doesn't seem much better or worse than incorrectly mistaking a Facebook post for a tweet. 
- Because I believe false positives and false negatives are equally as bad, I'd probably use accuracy.
</details>

### Remember: Score in this model is ACCURACY!!

In [25]:
# Score our model on the training set.

model.score(X_train_cvec, y_train)

0.8597926895799236

In [26]:
# Score our model on the testing set.

model.score(X_test_cvec, y_test)

0.8576104746317512

<details><summary> What should we do in this case? </summary>

- Our model appears *slightly* overfit. We could:
    - try to collect more data, 
    - try using fewer features by setting `max_features` to a smaller number when instantiating our CountVectorizer,
    - try TF-IDF Vectorizer,
    - try a non-default prior **if you have subject-matter expertise**.
- Rather than regularizing, [online answers](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) suggest using a different model entirely.
- Our training performance and testing performance are pretty close, though, so there may not be a lot of changes required.
</details>

In [27]:
# Import the confusion matrix function.

from sklearn.metrics import confusion_matrix

In [28]:
# Generate a confusion matrix.

confusion_matrix(y_test, predictions)

array([[553,  71],
       [103, 495]])

In [29]:
tn, fp, fn, tp = confusion_matrix(y_test, predictions).ravel()

In [30]:
print("True Negatives: %s" % tn)
print("False Positives: %s" % fp)
print("False Negatives: %s" % fn)
print("True Positives: %s" % tp)

True Negatives: 553
False Positives: 71
False Negatives: 103
True Positives: 495


<details><summary> By default, what does a true negative mean here? </summary>

- True negatives are things we correctly predict to be negative.
- In this case, since Twitter = 1, a true negative means I correctly predict something is a Facebook post.
</details>

---

<details><summary> By default, what does a false positive mean here? </summary>

- False positives are things we falsely predict to be positive.
- In this case, since Twitter = 1, a false positive means I incorrectly preidct something is a tweet (when it's really a Facebook post).
</details>

In [38]:
import numpy as np

In [31]:
model.feature_log_prob_

array([[ -6.7892577 ,  -6.68389719,  -7.4060319 ,  -7.46665653,
         -6.71288472,  -6.5756836 ,  -7.32147452,  -5.21536473,
         -7.37704437,  -7.0005668 ,  -5.80249371,  -7.10375103,
         -7.43588487,  -7.0005668 ,  -7.34887349,  -7.10375103,
         -7.02036942,  -7.46665653,  -7.04057213,  -7.34887349,
         -7.63655556,  -7.7135166 ,  -7.26883078,  -5.4434547 ,
         -7.46665653,  -7.43588487,  -6.60165909,  -7.5650966 ,
         -6.20500461,  -7.26883078,  -6.61490432,  -5.99075001,
         -6.08036216, -10.93239243,  -5.5030468 ,  -3.15963971,
         -7.93666016,  -7.24351297,  -7.21882036,  -6.96210052,
         -4.98959305,  -7.43588487,  -7.84134998,  -7.49840522,
         -5.05465665,  -4.61162413,  -7.7135166 ,  -6.74273769,
         -4.8897596 ,  -7.29480627,  -6.19619398,  -7.14820279,
         -6.98114871,  -6.75800516,  -7.46665653,  -6.98114871,
         -7.04057213,  -7.21882036,  -5.82644695,  -7.34887349,
         -7.02036942,  -7.84134998,  -7.

In [33]:
model.feature_log_prob_[0] # <--- (log) probabilities of respective words | facebook


array([ -6.7892577 ,  -6.68389719,  -7.4060319 ,  -7.46665653,
        -6.71288472,  -6.5756836 ,  -7.32147452,  -5.21536473,
        -7.37704437,  -7.0005668 ,  -5.80249371,  -7.10375103,
        -7.43588487,  -7.0005668 ,  -7.34887349,  -7.10375103,
        -7.02036942,  -7.46665653,  -7.04057213,  -7.34887349,
        -7.63655556,  -7.7135166 ,  -7.26883078,  -5.4434547 ,
        -7.46665653,  -7.43588487,  -6.60165909,  -7.5650966 ,
        -6.20500461,  -7.26883078,  -6.61490432,  -5.99075001,
        -6.08036216, -10.93239243,  -5.5030468 ,  -3.15963971,
        -7.93666016,  -7.24351297,  -7.21882036,  -6.96210052,
        -4.98959305,  -7.43588487,  -7.84134998,  -7.49840522,
        -5.05465665,  -4.61162413,  -7.7135166 ,  -6.74273769,
        -4.8897596 ,  -7.29480627,  -6.19619398,  -7.14820279,
        -6.98114871,  -6.75800516,  -7.46665653,  -6.98114871,
        -7.04057213,  -7.21882036,  -5.82644695,  -7.34887349,
        -7.02036942,  -7.84134998,  -7.49840522,  -7.43

In [34]:
model.feature_log_prob_[1] # <--- (log) probabilities of respective words | twitter


array([-7.18946958, -6.25993362, -7.25846245, -7.7002952 , -7.00714802,
       -8.10576031, -6.85299734, -5.19703941, -7.41261313, -7.49962451,
       -5.72313251, -7.33257042, -6.71946595, -7.7002952 , -8.79890749,
       -7.41261313, -6.76202556, -7.59493469, -6.85299734, -9.2043726 ,
       -7.06430644, -7.00714802, -7.33257042, -5.51549315, -8.28808187,
       -8.28808187, -7.95160963, -7.49962451, -6.4963224 , -7.59493469,
       -6.76202556, -6.25993362, -6.23395813, -4.15772687, -6.15985016,
       -4.13232868, -7.18946958, -8.10576031, -6.9530808 , -7.25846245,
       -5.33317159, -7.95160963, -7.33257042, -8.28808187, -5.81998234,
       -4.46379778, -7.59493469, -6.90178751, -4.96304585, -7.49962451,
       -6.85299734, -7.59493469, -6.9530808 , -8.28808187, -7.49962451,
       -7.12493106, -7.41261313, -7.7002952 , -5.51549315, -7.95160963,
       -6.76202556, -7.25846245, -7.81807824, -8.10576031, -7.59493469,
       -6.31400084, -7.12493106, -7.25846245, -5.8901866 , -5.38

In [37]:
log_prob_difference = model.feature_log_prob_[1] - model.feature_log_prob_[0]

In [40]:
type(log_prob_difference)

numpy.ndarray

In [47]:
# log probabilities of different the words

for word, val in zip(cvec.get_feature_names(), log_prob_difference):
    print(word, round(val, 4), round(np.exp(val), 4))

000 -0.4002 0.6702
10 0.424 1.528
11 0.1476 1.159
12 -0.2336 0.7916
2013 -0.2943 0.7451
2014 -1.5301 0.2165
30 0.4685 1.5976
about 0.0183 1.0185
access -0.0356 0.9651
across -0.4991 0.6071
act 0.0794 1.0826
action -0.2288 0.7955
address 0.7164 2.0471
administration -0.6997 0.4967
affairs -1.45 0.2346
affordable -0.3089 0.7343
after 0.2583 1.2948
again -0.1283 0.8796
against 0.1876 1.2063
agency -1.8555 0.1564
ago 0.5722 1.7722
agree 0.7064 2.0266
air -0.0637 0.9382
all -0.072 0.9305
allow -0.8214 0.4398
already -0.8522 0.4265
also -1.35 0.2593
always 0.0655 1.0677
am -0.2913 0.7473
amendment -0.3261 0.7217
america -0.1471 0.8632
american -0.2692 0.764
americans -0.1536 0.8576
amp 6.7747 875.3865
an -0.6568 0.5185
and -0.9727 0.3781
anniversary 0.7472 2.1111
annual -0.8622 0.4222
another 0.2657 1.3044
any -0.2964 0.7435
are -0.3436 0.7092
area -0.5157 0.5971
around 0.5088 1.6633
article -0.7897 0.454
as -0.7653 0.4652
at 0.1478 1.1593
award 0.1186 1.1259
back -0.159 0.853
be -0.0733 0.9